name: transcription_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - mamba
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - napari
  - pandas
  - trackpy
  - jupyterlab
  - pytorch
  - numba
  - ca-certificates
  - certifi
  - openssl
  - jpype1
  - pip
  - jupyterlab_code_formatter
  - black
  - isort
  - autopep8
  - multiprocess
  - ray-default
  - ipywidgets
  - pipreqs
  - deprecation
  - pip
    - -r requirements.txt
