name: ms2_pipeline_lite
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - matplotlib
  - numpy
  - dask
  - dask-image
  - scipy
  - trackpy
  - pandas
  - tqdm
  - magicgui
  - scyjava
  - setuptools
  - pip
  - pip:
    - zarr>2
    - napari
    - napari-ome-zarr
    - bioio
    - bioio-czi
    - bioio-dv
    - bioio-imageio
    - bioio-lif
    - bioio-nd2
    - bioio-ome-tiff
    - bioio-ome-zarr
    - bioio-sldy
    - bioio-tifffile
    - bioio-tiff-glob
    - bioio-bioformats