name: transcription_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - matplotlib
  - napari
  - trackpy
  - jupyterlab
  - numba
  - jpype1
  - pip
  - jupyterlab_code_formatter
  - black
  - ipywidgets
  - pipreqs
  - ipympl
  - build
  - pip:
      - -r requirements.txt
